### ISSUE TITLE
Subcomponent & Dependency between ActivityComponent & ApplicationComponent

### ISSUE THREAD

**Issue by ashraffouad** [ribot/ribot-app-android#15]
Hi,
I have been checking the code for "android-boilerplate" as template for new project, and this project "ribot-app-android" as sample implementation utilizing same project.

I really admire all the work done in "android-boilerplate" & I consider one of the best (If not the best) samples of complete typical Android application.

I have a question regarding these two projects trying to understand:
- In "ribot-app-android" there is dependency between ActivityComponent & ApplicationComponent but in "android-boilerplate" I don't find such relation but I find Subcomponent definition.
May I know why?

Thanks in advance.

**Comment by jemmaSlater** [comment]
Hello! Yes, the two projects have slightly different purposes as follows:

The "ribot-app-android" project is a more in depth example of how we worked on an internal project based upon our boilerplate. Although initially based on the boilerplate at the time, this sample project is not currently being maintained or updated alongside the boilerplate project as it stands.

The "android-boilerplate" project is an evolving effort to try and maintain an up-to-date boilerplate from which to start new projects from. The pull request where we introduced the Subcomponent to the boilerplate can be found here: https://github.com/ribot/android-boilerplate/pull/47

**Comment by ashraffouad** [comment]
Thanks.

Is there any intention to open issues for public to "android-boilerplate" to be able to ask question related to this project?

**Comment by jemmaSlater** [comment]
Due to the nature of the "android-boilerplate" project being just that, a boilerplate, the way we see it is that it is just a starting point from which we, and the community, can use as a basis from which to start new projects. The project is not intended to showcase any features, just acts as an example of a starting point. We expect developers to edit and adapt the project to their own project requirements.

We are open to collaboration and help through the means of pull requests to help keep it up to date, and to suggest better ways of doing things. Enabling Issues is something we have thought about, but decided against at this stage. There is an overview of the project setup in the readme. Specific questions about the functionality of any library used, or discussion about architecture, may be better suited for Stack Overflow, or discussion forums such as https://www.reddit.com/r/androiddev/ 🙂
